### ISSUE TITLE
Create TermBase

### ISSUE THREAD

**Issue by WinerWang** [byutrg/baseterm#67]
i wanna create termbase at localhost，but project throw the bug.how can i create a new termbase?

![qq 20170914135219](https://user-images.githubusercontent.com/10083492/30414007-0c11a2a0-9954-11e7-9d95-5dcf2419bb85.png)

**Comment by byutrg** [comment]
Hello @WinerWang, 

There were some instructions missing from the Readme.  BaseTerm works with an API which manages the storage of the termbase information.  We have been working on a PHP API that can more easily be installed, but for now you will have to use the CRITI API: [https://github.com/LexTerm/CRITI/tree/master/server](https://github.com/LexTerm/CRITI/tree/master/server)

We also updated BaseTerm that after you install the CRITI API, you will need to provide the URL to the API in the parameters.yml file:

```
#app/config/parameters.yml
parameters:
    termbase_api_location:  localhost:6543
```

The default for the CRITI api is localhost:6543.

Thanks for pointing out this missing piece of critical information!

**Comment by byutrg** [comment]
We just released the PHP API here: https://github.com/byutrg/baseterm-api

It may be easier to install, but may also have more bugs.
